### ISSUE TITLE
Disable Rotation on "grabbed" Object

### ISSUE THREAD

**Issue by nothingAD** [hecomi/VrGrabber#6]
Hey,

first of thanks you for providing such a good asset, honestly it works better than the oculus grabber.

Now on to my question. Maybe you have some hint on how to solve my problem.
I want a grabbale not rotating when i grab it. So that the upside always faces on world up. 
What i did so far is to set the SetRotation(Quaternion dest) with SetLookRotation(Vector3.forward, Vector3.up) thats what i want but than the object always moves to the end of the line and doesnt respond to the inputs or only response if i'm looking at a specifc angle.

![grabber](https://user-images.githubusercontent.com/43895614/55726264-a756be80-5a0f-11e9-820b-e7bcb3d9e61a.PNG)

Thank you and keep up the good work

Best regards
David

**Comment by Tillomaticus** [comment]
Hi David, 
you can freeze the constraints of the rigidbody. In the grabber you can then check for those constraints  and manually "overwrite" the rotation value for the frozen constraint with the original rotation value of the grabbed object. I think this should work for your problem.

Note: constraints are stored bitwise. So if you are familiar with how to use them you can write your own function to check for the bits instead for the whole number.

Hope this helps you
Tillomaticus




in FixedUpdateGrabbingObjectBySingleHand()
```
           //if constraints != none, manually overwrite rotation
            if (grabbable.rigidbody.constraints != RigidbodyConstraints.None)
                rot = FreezeRotation(rot, grabbable);

            FixedUpdateGrabbingObjectTransform(pos, rot, grabbable.transform.localScale);

```

my FreezeRotation()

```
//Overwrites the rotation
        //uses rigidbody constrains
        Quaternion FreezeRotation(Quaternion rot, VrgGrabbable grabbable)
        {
            Vector3 tempAngles = rot.eulerAngles;
            Vector3 grabbableRotAngles = grabbable.rotation.eulerAngles;

            //get constraints enum and convert to int
            //every constraints adds a power of 2 to the value
            //freeze for x-transform = 2, yT = 4, zT = 8
            //freeze for x-rotation = 16, yR = 32, zR = 64
            // combo for all rotations = 16+32+64 = 112
            // combo for xRot + yTranslate freeze = 16+4 = 20
            int x = (int)grabbable.rigidbody.constraints;

            //for every axis
            for(int i=6; i>0; i--)
            {
                // if remaining constraints are empty we can end
                if (x <= 0)
                    break;

                //check if x is bigger than 2^(2*i)  [64 for first case]
                //if so, subtract 2^(2*i) and thus eliminate that freeze from the total constraints
                //then add that freeze to the actual angles by overwriting the rotation with the original rotation
                if (x >= (int)Mathf.Pow(2,i))
                {
                    x -= (int)Mathf.Pow(2, i);

                    switch(i)
                    {
                        case 6:
                            tempAngles = new Vector3(tempAngles.x, tempAngles.y, grabbableRotAngles.z);
                            break;
                        case 5:
                            tempAngles = new Vector3(tempAngles.x, grabbableRotAngles.y, tempAngles.z);
                            break;
                        case 4:
                            tempAngles = new Vector3(grabbableRotAngles.x, tempAngles.y, tempAngles.z);
                            break;
                    }
                }
            }

            rot = Quaternion.Euler(tempAngles);
            return rot;
        }

```

**Comment by nothingAD** [comment]
Oh thank you so much, this looks like the solution for my problem! I'll implement it tomorrow and let you now how it worked out. 
Thank you so much for your help!

**Comment by nothingAD** [comment]
Hey @Tillomaticus thank you so much for your help! It works perfect! 
I think the player rotation while grabbing an object, makes the object move away from the player position.. But i have to do more research on this issue.
